### ISSUE TITLE
[FEAT] 내 여행 보기 뷰 구현

### ISSUE THREAD

**Issue by Larry7939** [SOPT-31-3/Triple-Android#10]
## 💡 Issue
내 여행 보기 뷰 구현

## 📝 todo
- [x] 프래그먼트 연결
- [x] 상단 바 구현
- [x] 3중첩 리사이클러 뷰 구현
  - [x] 도시별 리사이클러 뷰 구현
  - [x] 일차별 중첩 리사이클러 뷰 구현
  - [x] 시간별 중첩 리사이클러 뷰 구현
- [x] 일정 화면이 펼쳐지는 애니메이션 구현
