### ISSUE TITLE
[FEAT] 도시 선택 뷰 구현

### ISSUE THREAD

**Issue by Larry7939** [SOPT-31-3/Triple-Android#4]
## 💡 Issue
도시 선택 뷰 구현

## 📝 todo

- [x] 패키지 분리
- [x] 도시선택 레이아웃 작성
- [x] 아이템 레이아웃 작성
- [x] 도시 아이템 리사이클러 뷰 구현 with GridLayout
